// 'use client';

import { GlobalContextProvider } from './context/store'
import './globals.css'
import { Inter } from 'next/font/google'

import {NextIntlClientProvider} from 'next-intl';
import {useLocale} from 'next-intl';
import {notFound} from 'next/navigation';
 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children , params
}: {
  children: React.ReactNode , params: any
}) {

  const locale = useLocale();
 
  let messages;
  try {
    messages = (await import(`./../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html  lang={locale}>
      <body className={inter.className}>
          <GlobalContextProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>
          </GlobalContextProvider>
        </body>
    </html>
  )
}
